homepage:
    pattern:  /
    defaults: { _controller: jobeet2.controller:indexAction, _format: html }
    requirements:   { _method: "GET" }

index:
    pattern:  /
    defaults: { _controller: job.controller:indexAction, _format: html }
    requirements:   { _method: "GET" }

show:
    pattern:  /{company}/{location}/{id}/{position}.{_format}
    defaults: { _controller: job.controller:showAction, _format: html }
    requirements:   { _method: "GET" }    

update:
    pattern:  /update/{id}.{_format}
    defaults: { _controller: job.controller:updateAction, _format: html }
    requirements:   { _method: "GET" }

new:
    pattern:  /new.{_format}
    defaults: { _controller: job.controller:newAction, _format: html }
    requirements:   { _method: "GET" }

delete:
    pattern:  /delete/{id}.{_format}
    defaults: { _controller: job.controller:deleteAction, _format: html }
    requirements:   { _method: "GET" }

edit:
    pattern:  /edit/{id}.{_format}
    defaults: { _controller: job.controller:editAction, _format: html }
    requirements:   { _method: "GET" }

create:
    pattern:  /create.{_format}
    defaults: { _controller: job.controller:createAction, _format: html }
    requirements:   { _method: "GET" }

category:
    pattern:  /category/{slug}.{_format}
    defaults: {_controller: category.controller:showAction, _format: html }
    requirements:   { _method: "GET" }
