# Application/HelloBundle/Resources/config/doctrine/metadata/orm/Application.HelloBundle.Entity.Affiliate.dcm.yml
Application\HelloBundle\Entity\Affiliate:
    type: entity
    table: affiliate
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            length: 255
        email:
            type: string
            length: 255
        token:
            type: string
            length: 255
        is_active:
            type: boolean
     
    manyToMany:
          categories:
              targetEntity: Category              
              joinTable:
                  name: category_affiliate
                  joinColumns:
                    affiliate_id:
                      referencedColumnName: id
                  inverseJoinColumns:
                    category_id:
                      referencedColumnName: id                      
              
