app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration

doctrine.dbal:
    driver:   pdo_mysql
    dbname:   Symfony2Jobbet
    user:     root
    password: carlos
doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        Jobbet2Bundle: ~
          #type: annotation
          #dir: "%kernel.root_dir%/../src/Application/Jobbet2Bundle/Entity"
          #prefix: Jobbet2Bundle\Entity



## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
