jobbet2:
    pattern:  /jobbet2.{_format}
    defaults: { _controller: Jobbet2Bundle:Jobbet2:index, _format: html }

index:
    pattern: /job/index.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:index, _format: html }

show:
    pattern: /job/show/{id}.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:show, _format: html }

update:
    pattern: /job/update/{id}.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:update, _format: html }

new:
    pattern: /job/new.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:new, _format: html }

delete:
    pattern: /job/delete{id}.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:delete, _format: html }

edit:
    pattern: /job/edit.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:edit, _format: html }

create:
    pattern: /job/create.{_format}
    defaults: { _controller: Jobbet2Bundle:Job:create, _format: html }
